! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!                                                                  
! Parameter Header File                                            
!                                                                  
! Generated by KPP-2.2.4 for Mistra symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/Kpp)                
! KPP is distributed under GPL, the general public licence         
!       (http://www.gnu.org/copyleft/gpl.html)                     
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            
!     With important contributions from:                           
!        M. Damian, Villanova University, USA                      
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
!                                                                  
! File                 : aer_Parameters.h                          
! Time                 : Wed Jul 14 18:27:00 2021                  
! Working directory    : /local/josue/Mistra_2019/src/mech         
! Equation file        : aer.k                                     
! Output root filename : aer                                       
!                                                                  
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




! NSPEC - Number of chemical species                               
      INTEGER NSPEC
      PARAMETER ( NSPEC = 262 )
! NVAR - Number of Variable species                                
      INTEGER NVAR
      PARAMETER ( NVAR = 257 )
! NVARACT - Number of Active species                               
      INTEGER NVARACT
      PARAMETER ( NVARACT = 250 )
! NFIX - Number of Fixed species                                   
      INTEGER NFIX
      PARAMETER ( NFIX = 5 )
! NREACT - Number of reactions                                     
      INTEGER NREACT
      PARAMETER ( NREACT = 979 )
! NVARST - Starting of variables in conc. vect.                    
      INTEGER NVARST
      PARAMETER ( NVARST = 1 )
! NFIXST - Starting of fixed in conc. vect.                        
      INTEGER NFIXST
      PARAMETER ( NFIXST = 258 )
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
      INTEGER LU_NONZERO
      PARAMETER ( LU_NONZERO = 6579 )

! Index declaration for variable species in C and VAR              
!   VAR(ind_spc) = C(ind_spc)                                      

      INTEGER ind_CH2I2
      PARAMETER ( ind_CH2I2 = 1 )
      INTEGER ind_CH2ClI
      PARAMETER ( ind_CH2ClI = 2 )
      INTEGER ind_CH2BrI
      PARAMETER ( ind_CH2BrI = 3 )
      INTEGER ind_DUMM1
      PARAMETER ( ind_DUMM1 = 4 )
      INTEGER ind_DUMM2
      PARAMETER ( ind_DUMM2 = 5 )
      INTEGER ind_ClONO
      PARAMETER ( ind_ClONO = 6 )
      INTEGER ind_ClO3
      PARAMETER ( ind_ClO3 = 7 )
      INTEGER ind_NHS
      PARAMETER ( ind_NHS = 8 )
      INTEGER ind_IO2ml1
      PARAMETER ( ind_IO2ml1 = 9 )
      INTEGER ind_IO2ml2
      PARAMETER ( ind_IO2ml2 = 10 )
      INTEGER ind_ACTAl1
      PARAMETER ( ind_ACTAl1 = 11 )
      INTEGER ind_DMSO2l1
      PARAMETER ( ind_DMSO2l1 = 12 )
      INTEGER ind_C2H5OHl1
      PARAMETER ( ind_C2H5OHl1 = 13 )
      INTEGER ind_XORl1
      PARAMETER ( ind_XORl1 = 14 )
      INTEGER ind_SORl1
      PARAMETER ( ind_SORl1 = 15 )
      INTEGER ind_ACTAl2
      PARAMETER ( ind_ACTAl2 = 16 )
      INTEGER ind_DMSO2l2
      PARAMETER ( ind_DMSO2l2 = 17 )
      INTEGER ind_DMSO2
      PARAMETER ( ind_DMSO2 = 18 )
      INTEGER ind_C2H5OHl2
      PARAMETER ( ind_C2H5OHl2 = 19 )
      INTEGER ind_XORl2
      PARAMETER ( ind_XORl2 = 20 )
      INTEGER ind_XOR
      PARAMETER ( ind_XOR = 21 )
      INTEGER ind_SORl2
      PARAMETER ( ind_SORl2 = 22 )
      INTEGER ind_NOl1
      PARAMETER ( ind_NOl1 = 23 )
      INTEGER ind_NOl2
      PARAMETER ( ind_NOl2 = 24 )
      INTEGER ind_IOl1
      PARAMETER ( ind_IOl1 = 25 )
      INTEGER ind_IOl2
      PARAMETER ( ind_IOl2 = 26 )
      INTEGER ind_Cl2O3
      PARAMETER ( ind_Cl2O3 = 27 )
      INTEGER ind_NH4pl1
      PARAMETER ( ind_NH4pl1 = 28 )
      INTEGER ind_NH3l1
      PARAMETER ( ind_NH3l1 = 29 )
      INTEGER ind_ICl2ml1
      PARAMETER ( ind_ICl2ml1 = 30 )
      INTEGER ind_IBr2ml1
      PARAMETER ( ind_IBr2ml1 = 31 )
      INTEGER ind_NH4pl2
      PARAMETER ( ind_NH4pl2 = 32 )
      INTEGER ind_NH3l2
      PARAMETER ( ind_NH3l2 = 33 )
      INTEGER ind_ICl2ml2
      PARAMETER ( ind_ICl2ml2 = 34 )
      INTEGER ind_IBr2ml2
      PARAMETER ( ind_IBr2ml2 = 35 )
      INTEGER ind_CHO2
      PARAMETER ( ind_CHO2 = 36 )
      INTEGER ind_HOSO2
      PARAMETER ( ind_HOSO2 = 37 )
      INTEGER ind_Br2O
      PARAMETER ( ind_Br2O = 38 )
      INTEGER ind_RBr
      PARAMETER ( ind_RBr = 39 )
      INTEGER ind_H2SO4
      PARAMETER ( ind_H2SO4 = 40 )
      INTEGER ind_HIO3
      PARAMETER ( ind_HIO3 = 41 )
      INTEGER ind_SPAN
      PARAMETER ( ind_SPAN = 42 )
      INTEGER ind_CH4
      PARAMETER ( ind_CH4 = 43 )
      INTEGER ind_C2H6
      PARAMETER ( ind_C2H6 = 44 )
      INTEGER ind_NO4ml1
      PARAMETER ( ind_NO4ml1 = 45 )
      INTEGER ind_NO4ml2
      PARAMETER ( ind_NO4ml2 = 46 )
      INTEGER ind_SO2l1
      PARAMETER ( ind_SO2l1 = 47 )
      INTEGER ind_HCll1
      PARAMETER ( ind_HCll1 = 48 )
      INTEGER ind_HBrl1
      PARAMETER ( ind_HBrl1 = 49 )
      INTEGER ind_SO2l2
      PARAMETER ( ind_SO2l2 = 50 )
      INTEGER ind_HCll2
      PARAMETER ( ind_HCll2 = 51 )
      INTEGER ind_HBrl2
      PARAMETER ( ind_HBrl2 = 52 )
      INTEGER ind_I2O2
      PARAMETER ( ind_I2O2 = 53 )
      INTEGER ind_RCl
      PARAMETER ( ind_RCl = 54 )
      INTEGER ind_BrNO2
      PARAMETER ( ind_BrNO2 = 55 )
      INTEGER ind_CH3SO3
      PARAMETER ( ind_CH3SO3 = 56 )
      INTEGER ind_O1D
      PARAMETER ( ind_O1D = 57 )
      INTEGER ind_CO2
      PARAMETER ( ind_CO2 = 58 )
      INTEGER ind_SOR
      PARAMETER ( ind_SOR = 59 )
      INTEGER ind_SO4l1
      PARAMETER ( ind_SO4l1 = 60 )
      INTEGER ind_CH2OHSO3ml1
      PARAMETER ( ind_CH2OHSO3ml1 = 61 )
      INTEGER ind_CH3SO2ml1
      PARAMETER ( ind_CH3SO2ml1 = 62 )
      INTEGER ind_CH2OHSO3ml2
      PARAMETER ( ind_CH2OHSO3ml2 = 63 )
      INTEGER ind_CH3SO2ml2
      PARAMETER ( ind_CH3SO2ml2 = 64 )
      INTEGER ind_INO2
      PARAMETER ( ind_INO2 = 65 )
      INTEGER ind_C2H5I
      PARAMETER ( ind_C2H5I = 66 )
      INTEGER ind_BrCl2ml1
      PARAMETER ( ind_BrCl2ml1 = 67 )
      INTEGER ind_Br2Clml1
      PARAMETER ( ind_Br2Clml1 = 68 )
      INTEGER ind_CH3I
      PARAMETER ( ind_CH3I = 69 )
      INTEGER ind_ClOHml1
      PARAMETER ( ind_ClOHml1 = 70 )
      INTEGER ind_IClBrml1
      PARAMETER ( ind_IClBrml1 = 71 )
      INTEGER ind_BrCl2ml2
      PARAMETER ( ind_BrCl2ml2 = 72 )
      INTEGER ind_Br2Clml2
      PARAMETER ( ind_Br2Clml2 = 73 )
      INTEGER ind_ClOHml2
      PARAMETER ( ind_ClOHml2 = 74 )
      INTEGER ind_C3H7I
      PARAMETER ( ind_C3H7I = 75 )
      INTEGER ind_IClBrml2
      PARAMETER ( ind_IClBrml2 = 76 )
      INTEGER ind_NH3
      PARAMETER ( ind_NH3 = 77 )
      INTEGER ind_SO3ml1
      PARAMETER ( ind_SO3ml1 = 78 )
      INTEGER ind_SO3ml2
      PARAMETER ( ind_SO3ml2 = 79 )
      INTEGER ind_SO4l2
      PARAMETER ( ind_SO4l2 = 80 )
      INTEGER ind_HONO
      PARAMETER ( ind_HONO = 81 )
      INTEGER ind_O2l1
      PARAMETER ( ind_O2l1 = 82 )
      INTEGER ind_O2l2
      PARAMETER ( ind_O2l2 = 83 )
      INTEGER ind_DMSOl1
      PARAMETER ( ind_DMSOl1 = 84 )
      INTEGER ind_CH3OHl1
      PARAMETER ( ind_CH3OHl1 = 85 )
      INTEGER ind_Cl2O2
      PARAMETER ( ind_Cl2O2 = 86 )
      INTEGER ind_ClNO2
      PARAMETER ( ind_ClNO2 = 87 )
      INTEGER ind_ACTA
      PARAMETER ( ind_ACTA = 88 )
      INTEGER ind_DMSOl2
      PARAMETER ( ind_DMSOl2 = 89 )
      INTEGER ind_CH3OHl2
      PARAMETER ( ind_CH3OHl2 = 90 )
      INTEGER ind_H2
      PARAMETER ( ind_H2 = 91 )
      INTEGER ind_ClOml1
      PARAMETER ( ind_ClOml1 = 92 )
      INTEGER ind_BrOml1
      PARAMETER ( ind_BrOml1 = 93 )
      INTEGER ind_ClOml2
      PARAMETER ( ind_ClOml2 = 94 )
      INTEGER ind_BrOml2
      PARAMETER ( ind_BrOml2 = 95 )
      INTEGER ind_HCO3ml1
      PARAMETER ( ind_HCO3ml1 = 96 )
      INTEGER ind_HCOOml1
      PARAMETER ( ind_HCOOml1 = 97 )
      INTEGER ind_HOI
      PARAMETER ( ind_HOI = 98 )
      INTEGER ind_PAN
      PARAMETER ( ind_PAN = 99 )
      INTEGER ind_HCO3ml2
      PARAMETER ( ind_HCO3ml2 = 100 )
      INTEGER ind_HCOOml2
      PARAMETER ( ind_HCOOml2 = 101 )
      INTEGER ind_HNO4
      PARAMETER ( ind_HNO4 = 102 )
      INTEGER ind_BrOHml1
      PARAMETER ( ind_BrOHml1 = 103 )
      INTEGER ind_HNO3l2
      PARAMETER ( ind_HNO3l2 = 104 )
      INTEGER ind_C2H5OH
      PARAMETER ( ind_C2H5OH = 105 )
      INTEGER ind_BrOHml2
      PARAMETER ( ind_BrOHml2 = 106 )
      INTEGER ind_HNO3l1
      PARAMETER ( ind_HNO3l1 = 107 )
      INTEGER ind_IRO2
      PARAMETER ( ind_IRO2 = 108 )
      INTEGER ind_HI
      PARAMETER ( ind_HI = 109 )
      INTEGER ind_HCOOHl1
      PARAMETER ( ind_HCOOHl1 = 110 )
      INTEGER ind_CH3S
      PARAMETER ( ind_CH3S = 111 )
      INTEGER ind_HCOOHl2
      PARAMETER ( ind_HCOOHl2 = 112 )
      INTEGER ind_CH3SO3H
      PARAMETER ( ind_CH3SO3H = 113 )
      INTEGER ind_DOMl1
      PARAMETER ( ind_DOMl1 = 114 )
      INTEGER ind_DOMl2
      PARAMETER ( ind_DOMl2 = 115 )
      INTEGER ind_ClRO2
      PARAMETER ( ind_ClRO2 = 116 )
      INTEGER ind_SO3
      PARAMETER ( ind_SO3 = 117 )
      INTEGER ind_INO3
      PARAMETER ( ind_INO3 = 118 )
      INTEGER ind_CO
      PARAMETER ( ind_CO = 119 )
      INTEGER ind_BrRO2
      PARAMETER ( ind_BrRO2 = 120 )
      INTEGER ind_IO3ml1
      PARAMETER ( ind_IO3ml1 = 121 )
      INTEGER ind_IO3ml2
      PARAMETER ( ind_IO3ml2 = 122 )
      INTEGER ind_CH3SO
      PARAMETER ( ind_CH3SO = 123 )
      INTEGER ind_CH3OOl2
      PARAMETER ( ind_CH3OOl2 = 124 )
      INTEGER ind_CH3OOl1
      PARAMETER ( ind_CH3OOl1 = 125 )
      INTEGER ind_CO3ml1
      PARAMETER ( ind_CO3ml1 = 126 )
      INTEGER ind_CO3ml2
      PARAMETER ( ind_CO3ml2 = 127 )
      INTEGER ind_ETO2
      PARAMETER ( ind_ETO2 = 128 )
      INTEGER ind_HSO5ml1
      PARAMETER ( ind_HSO5ml1 = 129 )
      INTEGER ind_HSO5ml2
      PARAMETER ( ind_HSO5ml2 = 130 )
      INTEGER ind_ICll1
      PARAMETER ( ind_ICll1 = 131 )
      INTEGER ind_ICll2
      PARAMETER ( ind_ICll2 = 132 )
      INTEGER ind_Cl2
      PARAMETER ( ind_Cl2 = 133 )
      INTEGER ind_H2O2
      PARAMETER ( ind_H2O2 = 134 )
      INTEGER ind_IBr
      PARAMETER ( ind_IBr = 135 )
      INTEGER ind_EO2
      PARAMETER ( ind_EO2 = 136 )
      INTEGER ind_DMOO
      PARAMETER ( ind_DMOO = 137 )
      INTEGER ind_OIO
      PARAMETER ( ind_OIO = 138 )
      INTEGER ind_HSO4ml1
      PARAMETER ( ind_HSO4ml1 = 139 )
      INTEGER ind_N2O5
      PARAMETER ( ind_N2O5 = 140 )
      INTEGER ind_NO2ml2
      PARAMETER ( ind_NO2ml2 = 141 )
      INTEGER ind_NO2ml1
      PARAMETER ( ind_NO2ml1 = 142 )
      INTEGER ind_ETHE
      PARAMETER ( ind_ETHE = 143 )
      INTEGER ind_DMSl2
      PARAMETER ( ind_DMSl2 = 144 )
      INTEGER ind_BrCll2
      PARAMETER ( ind_BrCll2 = 145 )
      INTEGER ind_BrCll1
      PARAMETER ( ind_BrCll1 = 146 )
      INTEGER ind_OClO
      PARAMETER ( ind_OClO = 147 )
      INTEGER ind_DMSl1
      PARAMETER ( ind_DMSl1 = 148 )
      INTEGER ind_ALD2
      PARAMETER ( ind_ALD2 = 149 )
      INTEGER ind_HOBr
      PARAMETER ( ind_HOBr = 150 )
      INTEGER ind_ROOH
      PARAMETER ( ind_ROOH = 151 )
      INTEGER ind_CH3SO2
      PARAMETER ( ind_CH3SO2 = 152 )
      INTEGER ind_NO3l2
      PARAMETER ( ind_NO3l2 = 153 )
      INTEGER ind_HIO2l2
      PARAMETER ( ind_HIO2l2 = 154 )
      INTEGER ind_NO3l1
      PARAMETER ( ind_NO3l1 = 155 )
      INTEGER ind_HIO2l1
      PARAMETER ( ind_HIO2l1 = 156 )
      INTEGER ind_HCHOl2
      PARAMETER ( ind_HCHOl2 = 157 )
      INTEGER ind_NO2l2
      PARAMETER ( ind_NO2l2 = 158 )
      INTEGER ind_HCHOl1
      PARAMETER ( ind_HCHOl1 = 159 )
      INTEGER ind_HOCl
      PARAMETER ( ind_HOCl = 160 )
      INTEGER ind_MCO3
      PARAMETER ( ind_MCO3 = 161 )
      INTEGER ind_NO2l1
      PARAMETER ( ind_NO2l1 = 162 )
      INTEGER ind_HCl
      PARAMETER ( ind_HCl = 163 )
      INTEGER ind_HBr
      PARAMETER ( ind_HBr = 164 )
      INTEGER ind_HSO4ml2
      PARAMETER ( ind_HSO4ml2 = 165 )
      INTEGER ind_CH3SO3ml2
      PARAMETER ( ind_CH3SO3ml2 = 166 )
      INTEGER ind_Br2l2
      PARAMETER ( ind_Br2l2 = 167 )
      INTEGER ind_Br2l1
      PARAMETER ( ind_Br2l1 = 168 )
      INTEGER ind_SO2
      PARAMETER ( ind_SO2 = 169 )
      INTEGER ind_Brl2
      PARAMETER ( ind_Brl2 = 170 )
      INTEGER ind_Brl1
      PARAMETER ( ind_Brl1 = 171 )
      INTEGER ind_CO2l2
      PARAMETER ( ind_CO2l2 = 172 )
      INTEGER ind_Iml2
      PARAMETER ( ind_Iml2 = 173 )
      INTEGER ind_Iml1
      PARAMETER ( ind_Iml1 = 174 )
      INTEGER ind_I2
      PARAMETER ( ind_I2 = 175 )
      INTEGER ind_SO4ml1
      PARAMETER ( ind_SO4ml1 = 176 )
      INTEGER ind_SO4ml2
      PARAMETER ( ind_SO4ml2 = 177 )
      INTEGER ind_CH3SO2H
      PARAMETER ( ind_CH3SO2H = 178 )
      INTEGER ind_CH3SO3ml1
      PARAMETER ( ind_CH3SO3ml1 = 179 )
      INTEGER ind_BrNO3
      PARAMETER ( ind_BrNO3 = 180 )
      INTEGER ind_ClNO3
      PARAMETER ( ind_ClNO3 = 181 )
      INTEGER ind_HONOl1
      PARAMETER ( ind_HONOl1 = 182 )
      INTEGER ind_HNO4l2
      PARAMETER ( ind_HNO4l2 = 183 )
      INTEGER ind_CH3OH
      PARAMETER ( ind_CH3OH = 184 )
      INTEGER ind_DMSO
      PARAMETER ( ind_DMSO = 185 )
      INTEGER ind_CO2l1
      PARAMETER ( ind_CO2l1 = 186 )
      INTEGER ind_HNO3
      PARAMETER ( ind_HNO3 = 187 )
      INTEGER ind_IBrl1
      PARAMETER ( ind_IBrl1 = 188 )
      INTEGER ind_ACO2
      PARAMETER ( ind_ACO2 = 189 )
      INTEGER ind_Cll2
      PARAMETER ( ind_Cll2 = 190 )
      INTEGER ind_Cll1
      PARAMETER ( ind_Cll1 = 191 )
      INTEGER ind_SO5ml2
      PARAMETER ( ind_SO5ml2 = 192 )
      INTEGER ind_SO5ml1
      PARAMETER ( ind_SO5ml1 = 193 )
      INTEGER ind_HOIl1
      PARAMETER ( ind_HOIl1 = 194 )
      INTEGER ind_DMS
      PARAMETER ( ind_DMS = 195 )
      INTEGER ind_I2l1
      PARAMETER ( ind_I2l1 = 196 )
      INTEGER ind_CH3OOHl2
      PARAMETER ( ind_CH3OOHl2 = 197 )
      INTEGER ind_HCHO
      PARAMETER ( ind_HCHO = 198 )
      INTEGER ind_SO42ml1
      PARAMETER ( ind_SO42ml1 = 199 )
      INTEGER ind_HONOl2
      PARAMETER ( ind_HONOl2 = 200 )
      INTEGER ind_HNO4l1
      PARAMETER ( ind_HNO4l1 = 201 )
      INTEGER ind_BrCl
      PARAMETER ( ind_BrCl = 202 )
      INTEGER ind_CH3OOHl1
      PARAMETER ( ind_CH3OOHl1 = 203 )
      INTEGER ind_IBrl2
      PARAMETER ( ind_IBrl2 = 204 )
      INTEGER ind_I2l2
      PARAMETER ( ind_I2l2 = 205 )
      INTEGER ind_HOIl2
      PARAMETER ( ind_HOIl2 = 206 )
      INTEGER ind_MO2
      PARAMETER ( ind_MO2 = 207 )
      INTEGER ind_O3
      PARAMETER ( ind_O3 = 208 )
      INTEGER ind_SO42ml2
      PARAMETER ( ind_SO42ml2 = 209 )
      INTEGER ind_HO2
      PARAMETER ( ind_HO2 = 210 )
      INTEGER ind_NO
      PARAMETER ( ind_NO = 211 )
      INTEGER ind_SO32ml2
      PARAMETER ( ind_SO32ml2 = 212 )
      INTEGER ind_O3l2
      PARAMETER ( ind_O3l2 = 213 )
      INTEGER ind_HO2l1
      PARAMETER ( ind_HO2l1 = 214 )
      INTEGER ind_HOBrl2
      PARAMETER ( ind_HOBrl2 = 215 )
      INTEGER ind_Cl2l1
      PARAMETER ( ind_Cl2l1 = 216 )
      INTEGER ind_Brml1
      PARAMETER ( ind_Brml1 = 217 )
      INTEGER ind_HSO3ml1
      PARAMETER ( ind_HSO3ml1 = 218 )
      INTEGER ind_OHl2
      PARAMETER ( ind_OHl2 = 219 )
      INTEGER ind_Cl2ml1
      PARAMETER ( ind_Cl2ml1 = 220 )
      INTEGER ind_Br2
      PARAMETER ( ind_Br2 = 221 )
      INTEGER ind_HOBrl1
      PARAMETER ( ind_HOBrl1 = 222 )
      INTEGER ind_HOCll1
      PARAMETER ( ind_HOCll1 = 223 )
      INTEGER ind_O3l1
      PARAMETER ( ind_O3l1 = 224 )
      INTEGER ind_Cl2l2
      PARAMETER ( ind_Cl2l2 = 225 )
      INTEGER ind_SO32ml1
      PARAMETER ( ind_SO32ml1 = 226 )
      INTEGER ind_Clml2
      PARAMETER ( ind_Clml2 = 227 )
      INTEGER ind_OHml2
      PARAMETER ( ind_OHml2 = 228 )
      INTEGER ind_NO3
      PARAMETER ( ind_NO3 = 229 )
      INTEGER ind_Hpl2
      PARAMETER ( ind_Hpl2 = 230 )
      INTEGER ind_OH
      PARAMETER ( ind_OH = 231 )
      INTEGER ind_H2O2l1
      PARAMETER ( ind_H2O2l1 = 232 )
      INTEGER ind_H2O2l2
      PARAMETER ( ind_H2O2l2 = 233 )
      INTEGER ind_Br2ml2
      PARAMETER ( ind_Br2ml2 = 234 )
      INTEGER ind_Br2ml1
      PARAMETER ( ind_Br2ml1 = 235 )
      INTEGER ind_Brml2
      PARAMETER ( ind_Brml2 = 236 )
      INTEGER ind_HSO3ml2
      PARAMETER ( ind_HSO3ml2 = 237 )
      INTEGER ind_O2ml1
      PARAMETER ( ind_O2ml1 = 238 )
      INTEGER ind_O3P
      PARAMETER ( ind_O3P = 239 )
      INTEGER ind_Cl
      PARAMETER ( ind_Cl = 240 )
      INTEGER ind_ClO
      PARAMETER ( ind_ClO = 241 )
      INTEGER ind_NO3ml2
      PARAMETER ( ind_NO3ml2 = 242 )
      INTEGER ind_Br
      PARAMETER ( ind_Br = 243 )
      INTEGER ind_BrO
      PARAMETER ( ind_BrO = 244 )
      INTEGER ind_I
      PARAMETER ( ind_I = 245 )
      INTEGER ind_IO
      PARAMETER ( ind_IO = 246 )
      INTEGER ind_HO2l2
      PARAMETER ( ind_HO2l2 = 247 )
      INTEGER ind_Hpl1
      PARAMETER ( ind_Hpl1 = 248 )
      INTEGER ind_NO3ml1
      PARAMETER ( ind_NO3ml1 = 249 )
      INTEGER ind_OHl1
      PARAMETER ( ind_OHl1 = 250 )
      INTEGER ind_NO2
      PARAMETER ( ind_NO2 = 251 )
      INTEGER ind_ICl
      PARAMETER ( ind_ICl = 252 )
      INTEGER ind_Clml1
      PARAMETER ( ind_Clml1 = 253 )
      INTEGER ind_HOCll2
      PARAMETER ( ind_HOCll2 = 254 )
      INTEGER ind_OHml1
      PARAMETER ( ind_OHml1 = 255 )
      INTEGER ind_Cl2ml2
      PARAMETER ( ind_Cl2ml2 = 256 )
      INTEGER ind_O2ml2
      PARAMETER ( ind_O2ml2 = 257 )

! Index declaration for fixed species in C                         
!   C(ind_spc)                                                     

      INTEGER ind_O2
      PARAMETER ( ind_O2 = 258 )
      INTEGER ind_H2O
      PARAMETER ( ind_H2O = 259 )
      INTEGER ind_N2
      PARAMETER ( ind_N2 = 260 )
      INTEGER ind_H2Ol1
      PARAMETER ( ind_H2Ol1 = 261 )
      INTEGER ind_H2Ol2
      PARAMETER ( ind_H2Ol2 = 262 )

! Index declaration for fixed species in FIX                       
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)                 

      INTEGER indf_O2
      PARAMETER ( indf_O2 = 1 )
      INTEGER indf_H2O
      PARAMETER ( indf_H2O = 2 )
      INTEGER indf_N2
      PARAMETER ( indf_N2 = 3 )
      INTEGER indf_H2Ol1
      PARAMETER ( indf_H2Ol1 = 4 )
      INTEGER indf_H2Ol2
      PARAMETER ( indf_H2Ol2 = 5 )
