C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C                                                                  
C Sparse Data Header File                                          
C                                                                  
C Generated by KPP-2.2.4 for Mistra symbolic chemistry Kinetics PreProcessor
C       (http://www.cs.vt.edu/~asandu/Software/Kpp)                
C KPP is distributed under GPL, the general public licence         
C       (http://www.gnu.org/copyleft/gpl.html)                     
C (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           
C (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            
C     With important contributions from:                           
C        M. Damian, Villanova University, USA                      
C        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
C                                                                  
C File                 : aer_Sparse.h                              
C Time                 : Wed Jul 14 18:27:00 2021                  
C Working directory    : /local/josue/Mistra_2019/src/mech         
C Equation file        : aer.k                                     
C Output root filename : aer                                       
C                                                                  
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




C  ----------> Sparse Jacobian Data                                

C LU_ICOL_a - Column indexes of the LU Jacobian of variables         
      INTEGER LU_ICOL_a(6579)
      COMMON /SDATA_a/ LU_ICOL_a
C LU_CROW_a - Compressed row indexes of the LU Jacobian of variables 
      INTEGER LU_CROW_a(258)
      COMMON /SDATA_a/ LU_CROW_a
C LU_DIAG_a - Diagonal indexes of the LU Jacobian of variables       
      INTEGER LU_DIAG_a(258)
      COMMON /SDATA_a/ LU_DIAG_a

