! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!                                                                  
! Global Data Header File                                          
!                                                                  
! Generated by KPP-2.2.4 for Mistra symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/Kpp)                
! KPP is distributed under GPL, the general public licence         
!       (http://www.gnu.org/copyleft/gpl.html)                     
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            
!     With important contributions from:                           
!        M. Damian, Villanova University, USA                      
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
!                                                                  
! File                 : aer_Global.h                              
! Time                 : Wed Jul 14 18:27:00 2021                  
! Working directory    : /local/josue/Mistra_2019/src/mech         
! Equation file        : aer.k                                     
! Output root filename : aer                                       
!                                                                  
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




! Declaration of global variables                                  

! C - Concentration of all species                                 
      REAL*8 C(NSPEC)
      COMMON /GDATA_a/ C
! VAR - Concentrations of variable species (global)                
      REAL*8 VAR(NVAR)
! FIX - Concentrations of fixed species (global)                   
      REAL*8 FIX(NFIX)
! VAR, FIX are chunks of array C                                   
      EQUIVALENCE( C(1),VAR(1) )
      EQUIVALENCE( C(258),FIX(1) )
! RCONST - Rate constants (global)                                 
      REAL*8 RCONST(NREACT)
      COMMON /GDATA_a/ RCONST
! TIME - Current integration time                                  
      REAL*8 TIME
      COMMON /GDATA_a/ TIME
! DT - Integration step                                            
      REAL*8 DT
      COMMON /GDATA_a/ DT
! ATOL - Absolute tolerance                                        
      REAL*8 ATOL(NVAR)
      COMMON /GDATA_a/ ATOL
! RTOL - Relative tolerance                                        
      REAL*8 RTOL(NVAR)
      COMMON /GDATA_a/ RTOL
! STEPMIN - Lower bound for integration step                       
      REAL*8 STEPMIN
      COMMON /GDATA_a/ STEPMIN
! STEPMAX - Upper bound for integration step                       
      REAL*8 STEPMAX
      COMMON /GDATA_a/ STEPMAX
! SPC_NAMES - Names of chemical species                            
      CHARACTER*32 SPC_NAMES(262)
      COMMON /CHARGDATA_a/ SPC_NAMES
! EQN_NAMES - Equation names                                       
      CHARACTER*100 EQN_NAMES(979)
      COMMON /CHARGDATA_a/ EQN_NAMES

! INLINED global variable declarations                             

! IMPORTANT: this file must comply with both F77 and F90 standards
!   - comment lines MUST start with an exclamation mark "!", not a "c" or "C"
!   - continuation lines MUST begin with an ampersand "&" in 6-th position, and the
!     previous line MUST end with an ampersand placed after the 72-nd position
!     (for homogeneity, please always use the 73-rd position)

! photolysis common block
      !  (if updated here, other *.def files for KPP and global param must be updated as well)
      integer, parameter :: nphrxn = 47
      common /ph_r_a/ ph_rat(nphrxn)
      double precision ph_rat

! conversion factors
      double precision yhenry,yxkmt,ykef,ykeb,yxkmtd,ycwd,yxeq,conv1,    &
     &    cvv1,cvv2,xhal,xiod,xliq1,xliq2,xhet1,xhet2,ycw,ykmt_OHClm
      common /kpp_rate_a/ yhenry(NSPEC),yxkmt(NSPEC,2),ykef(NSPEC,2),    &
     &    ykeb(NSPEC,2),yxkmtd(NSPEC,2),yxeq(NSPEC),ycw(2),ycwd(2),      &
     &    conv1,cvv1,cvv2,xhal,xiod,xliq1,xliq2,xhet1,xhet2
      common /k_surf_a/ ykmt_OHClm(2)


! INLINED global variable declarations                             

