! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!                                                                  
! Parameter Header File                                            
!                                                                  
! Generated by KPP-2.2.4 for Mistra symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/Kpp)                
! KPP is distributed under GPL, the general public licence         
!       (http://www.gnu.org/copyleft/gpl.html)                     
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            
!     With important contributions from:                           
!        M. Damian, Villanova University, USA                      
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
!                                                                  
! File                 : gas_Parameters.h                          
! Time                 : Wed Jul 14 18:26:57 2021                  
! Working directory    : /local/josue/Mistra_2019/src/mech         
! Equation file        : gas.k                                     
! Output root filename : gas                                       
!                                                                  
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




! NSPEC - Number of chemical species                               
      INTEGER NSPEC
      PARAMETER ( NSPEC = 105 )
! NVAR - Number of Variable species                                
      INTEGER NVAR
      PARAMETER ( NVAR = 102 )
! NVARACT - Number of Active species                               
      INTEGER NVARACT
      PARAMETER ( NVARACT = 87 )
! NFIX - Number of Fixed species                                   
      INTEGER NFIX
      PARAMETER ( NFIX = 3 )
! NREACT - Number of reactions                                     
      INTEGER NREACT
      PARAMETER ( NREACT = 331 )
! NVARST - Starting of variables in conc. vect.                    
      INTEGER NVARST
      PARAMETER ( NVARST = 1 )
! NFIXST - Starting of fixed in conc. vect.                        
      INTEGER NFIXST
      PARAMETER ( NFIXST = 103 )
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
      INTEGER LU_NONZERO
      PARAMETER ( LU_NONZERO = 1110 )

! Index declaration for variable species in C and VAR              
!   VAR(ind_spc) = C(ind_spc)                                      

      INTEGER ind_CH2I2
      PARAMETER ( ind_CH2I2 = 1 )
      INTEGER ind_CH2ClI
      PARAMETER ( ind_CH2ClI = 2 )
      INTEGER ind_CH2BrI
      PARAMETER ( ind_CH2BrI = 3 )
      INTEGER ind_DUMM1
      PARAMETER ( ind_DUMM1 = 4 )
      INTEGER ind_CO2
      PARAMETER ( ind_CO2 = 5 )
      INTEGER ind_DMSO2
      PARAMETER ( ind_DMSO2 = 6 )
      INTEGER ind_CH3SO3H
      PARAMETER ( ind_CH3SO3H = 7 )
      INTEGER ind_ClONO
      PARAMETER ( ind_ClONO = 8 )
      INTEGER ind_ClO3
      PARAMETER ( ind_ClO3 = 9 )
      INTEGER ind_HIO3
      PARAMETER ( ind_HIO3 = 10 )
      INTEGER ind_NHS
      PARAMETER ( ind_NHS = 11 )
      INTEGER ind_XOR
      PARAMETER ( ind_XOR = 12 )
      INTEGER ind_HNO3l1
      PARAMETER ( ind_HNO3l1 = 13 )
      INTEGER ind_NH3l1
      PARAMETER ( ind_NH3l1 = 14 )
      INTEGER ind_SO4l1
      PARAMETER ( ind_SO4l1 = 15 )
      INTEGER ind_HNO3l2
      PARAMETER ( ind_HNO3l2 = 16 )
      INTEGER ind_NH3l2
      PARAMETER ( ind_NH3l2 = 17 )
      INTEGER ind_SO4l2
      PARAMETER ( ind_SO4l2 = 18 )
      INTEGER ind_H2SO4
      PARAMETER ( ind_H2SO4 = 19 )
      INTEGER ind_I2O2
      PARAMETER ( ind_I2O2 = 20 )
      INTEGER ind_Cl2O3
      PARAMETER ( ind_Cl2O3 = 21 )
      INTEGER ind_BrNO2
      PARAMETER ( ind_BrNO2 = 22 )
      INTEGER ind_CHO2
      PARAMETER ( ind_CHO2 = 23 )
      INTEGER ind_NH3
      PARAMETER ( ind_NH3 = 24 )
      INTEGER ind_HOSO2
      PARAMETER ( ind_HOSO2 = 25 )
      INTEGER ind_SO3
      PARAMETER ( ind_SO3 = 26 )
      INTEGER ind_CH3SO3
      PARAMETER ( ind_CH3SO3 = 27 )
      INTEGER ind_HONO
      PARAMETER ( ind_HONO = 28 )
      INTEGER ind_Br2O
      PARAMETER ( ind_Br2O = 29 )
      INTEGER ind_INO2
      PARAMETER ( ind_INO2 = 30 )
      INTEGER ind_RBr
      PARAMETER ( ind_RBr = 31 )
      INTEGER ind_N2O5
      PARAMETER ( ind_N2O5 = 32 )
      INTEGER ind_SPAN
      PARAMETER ( ind_SPAN = 33 )
      INTEGER ind_CH4
      PARAMETER ( ind_CH4 = 34 )
      INTEGER ind_C2H6
      PARAMETER ( ind_C2H6 = 35 )
      INTEGER ind_HOI
      PARAMETER ( ind_HOI = 36 )
      INTEGER ind_RCl
      PARAMETER ( ind_RCl = 37 )
      INTEGER ind_O1D
      PARAMETER ( ind_O1D = 38 )
      INTEGER ind_SOR
      PARAMETER ( ind_SOR = 39 )
      INTEGER ind_ClNO2
      PARAMETER ( ind_ClNO2 = 40 )
      INTEGER ind_HNO4
      PARAMETER ( ind_HNO4 = 41 )
      INTEGER ind_CH3SO2H
      PARAMETER ( ind_CH3SO2H = 42 )
      INTEGER ind_HI
      PARAMETER ( ind_HI = 43 )
      INTEGER ind_INO3
      PARAMETER ( ind_INO3 = 44 )
      INTEGER ind_CH3I
      PARAMETER ( ind_CH3I = 45 )
      INTEGER ind_C3H7I
      PARAMETER ( ind_C3H7I = 46 )
      INTEGER ind_C2H5I
      PARAMETER ( ind_C2H5I = 47 )
      INTEGER ind_ACTA
      PARAMETER ( ind_ACTA = 48 )
      INTEGER ind_CO
      PARAMETER ( ind_CO = 49 )
      INTEGER ind_H2
      PARAMETER ( ind_H2 = 50 )
      INTEGER ind_BrNO3
      PARAMETER ( ind_BrNO3 = 51 )
      INTEGER ind_SO2
      PARAMETER ( ind_SO2 = 52 )
      INTEGER ind_Cl2O2
      PARAMETER ( ind_Cl2O2 = 53 )
      INTEGER ind_ACO2
      PARAMETER ( ind_ACO2 = 54 )
      INTEGER ind_OIO
      PARAMETER ( ind_OIO = 55 )
      INTEGER ind_CH3OH
      PARAMETER ( ind_CH3OH = 56 )
      INTEGER ind_PAN
      PARAMETER ( ind_PAN = 57 )
      INTEGER ind_IBr
      PARAMETER ( ind_IBr = 58 )
      INTEGER ind_IRO2
      PARAMETER ( ind_IRO2 = 59 )
      INTEGER ind_C2H5OH
      PARAMETER ( ind_C2H5OH = 60 )
      INTEGER ind_CH3S
      PARAMETER ( ind_CH3S = 61 )
      INTEGER ind_HOCl
      PARAMETER ( ind_HOCl = 62 )
      INTEGER ind_ClNO3
      PARAMETER ( ind_ClNO3 = 63 )
      INTEGER ind_HBr
      PARAMETER ( ind_HBr = 64 )
      INTEGER ind_ClRO2
      PARAMETER ( ind_ClRO2 = 65 )
      INTEGER ind_HCl
      PARAMETER ( ind_HCl = 66 )
      INTEGER ind_H2O2
      PARAMETER ( ind_H2O2 = 67 )
      INTEGER ind_HOBr
      PARAMETER ( ind_HOBr = 68 )
      INTEGER ind_ICl
      PARAMETER ( ind_ICl = 69 )
      INTEGER ind_BrRO2
      PARAMETER ( ind_BrRO2 = 70 )
      INTEGER ind_ETO2
      PARAMETER ( ind_ETO2 = 71 )
      INTEGER ind_Cl2
      PARAMETER ( ind_Cl2 = 72 )
      INTEGER ind_EO2
      PARAMETER ( ind_EO2 = 73 )
      INTEGER ind_Br2
      PARAMETER ( ind_Br2 = 74 )
      INTEGER ind_HNO3
      PARAMETER ( ind_HNO3 = 75 )
      INTEGER ind_ETHE
      PARAMETER ( ind_ETHE = 76 )
      INTEGER ind_DMSO
      PARAMETER ( ind_DMSO = 77 )
      INTEGER ind_ROOH
      PARAMETER ( ind_ROOH = 78 )
      INTEGER ind_ALD2
      PARAMETER ( ind_ALD2 = 79 )
      INTEGER ind_BrCl
      PARAMETER ( ind_BrCl = 80 )
      INTEGER ind_I2
      PARAMETER ( ind_I2 = 81 )
      INTEGER ind_MCO3
      PARAMETER ( ind_MCO3 = 82 )
      INTEGER ind_OClO
      PARAMETER ( ind_OClO = 83 )
      INTEGER ind_CH3SO
      PARAMETER ( ind_CH3SO = 84 )
      INTEGER ind_CH3SO2
      PARAMETER ( ind_CH3SO2 = 85 )
      INTEGER ind_DMOO
      PARAMETER ( ind_DMOO = 86 )
      INTEGER ind_DMS
      PARAMETER ( ind_DMS = 87 )
      INTEGER ind_HCHO
      PARAMETER ( ind_HCHO = 88 )
      INTEGER ind_I
      PARAMETER ( ind_I = 89 )
      INTEGER ind_O3P
      PARAMETER ( ind_O3P = 90 )
      INTEGER ind_NO2
      PARAMETER ( ind_NO2 = 91 )
      INTEGER ind_BrO
      PARAMETER ( ind_BrO = 92 )
      INTEGER ind_NO
      PARAMETER ( ind_NO = 93 )
      INTEGER ind_O3
      PARAMETER ( ind_O3 = 94 )
      INTEGER ind_NO3
      PARAMETER ( ind_NO3 = 95 )
      INTEGER ind_ClO
      PARAMETER ( ind_ClO = 96 )
      INTEGER ind_Br
      PARAMETER ( ind_Br = 97 )
      INTEGER ind_OH
      PARAMETER ( ind_OH = 98 )
      INTEGER ind_Cl
      PARAMETER ( ind_Cl = 99 )
      INTEGER ind_MO2
      PARAMETER ( ind_MO2 = 100 )
      INTEGER ind_IO
      PARAMETER ( ind_IO = 101 )
      INTEGER ind_HO2
      PARAMETER ( ind_HO2 = 102 )

! Index declaration for fixed species in C                         
!   C(ind_spc)                                                     

      INTEGER ind_O2
      PARAMETER ( ind_O2 = 103 )
      INTEGER ind_H2O
      PARAMETER ( ind_H2O = 104 )
      INTEGER ind_N2
      PARAMETER ( ind_N2 = 105 )

! Index declaration for fixed species in FIX                       
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)                 

      INTEGER indf_O2
      PARAMETER ( indf_O2 = 1 )
      INTEGER indf_H2O
      PARAMETER ( indf_H2O = 2 )
      INTEGER indf_N2
      PARAMETER ( indf_N2 = 3 )
