C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C                                                                  
C Sparse Data Header File                                          
C                                                                  
C Generated by KPP-2.2.4 for Mistra symbolic chemistry Kinetics PreProcessor
C       (http://www.cs.vt.edu/~asandu/Software/Kpp)                
C KPP is distributed under GPL, the general public licence         
C       (http://www.gnu.org/copyleft/gpl.html)                     
C (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           
C (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            
C     With important contributions from:                           
C        M. Damian, Villanova University, USA                      
C        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
C                                                                  
C File                 : tot_Sparse.h                              
C Time                 : Wed Jul 14 18:27:05 2021                  
C Working directory    : /local/josue/Mistra_2019/src/mech         
C Equation file        : tot.k                                     
C Output root filename : tot                                       
C                                                                  
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




C  ----------> Sparse Jacobian Data                                

C LU_ICOL_t - Column indexes of the LU Jacobian of variables         
      INTEGER LU_ICOL_t(13503)
      COMMON /SDATA_t/ LU_ICOL_t
C LU_CROW_t - Compressed row indexes of the LU Jacobian of variables 
      INTEGER LU_CROW_t(418)
      COMMON /SDATA_t/ LU_CROW_t
C LU_DIAG_t - Diagonal indexes of the LU Jacobian of variables       
      INTEGER LU_DIAG_t(418)
      COMMON /SDATA_t/ LU_DIAG_t

